name: Deploy files to staging cdn

on: workflow_dispatch

permissions: 
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deply files to staging cdn
    runs-on: ubuntu-latest
    environment: stagingcdn
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Azure login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ secrets.AZURE_STAGING_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Run release script
      env:
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        AZCOPY_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        bash .github/scripts/release.sh \
          --source . \
          --azure-sync-cdn \
          --azure-sa-name "${{ secrets.STAGING_STORAGEACCOUNT_NAME }}"
